const Data = [
  {
    id: 1,
    name: "Clinton Biswas",
    username: "ponti3343",
    phone: "01726288542",
    email: "ponti@gmail.com",
    status: "active",
  },
  {
    id: 2,
    name: "Ponti Biswas",
    username: "clinton3343",
    phone: "4532134567",
    email: "clinton@gmail.com",
    status: "inactive",
  },
  {
    id: 3,
    name: "Anik Biswas",
    username: "Anik3343",
    phone: "765431987",
    email: "anik@gmail.com",
    status: "active",
  },
  {
    id: 4,
    name: "Alex Biswas",
    username: "Alex3343",
    phone: "9876543567",
    email: "alex@gmail.com",
    status: "active",
  },
  {
    id: 5,
    name: "Nazirul Biswas",
    username: "Nazirul3343",
    phone: "8765748865",
    email: "nazirul@gmail.com",
    status: "inactive",
  },
  {
    id: 6,
    name: "Shohag Biswas",
    username: "shohag3343",
    phone: "654328765",
    email: "bala@gmail.com",
    status: "active",
  },
  {
    id: 7,
    name: "Sourav Biswas",
    username: "sourav",
    phone: "987654323",
    email: "sourav@gmail.com",
    status: "active",
  },
  {
    id: 8,
    name: "Shayon Biswas",
    username: "shayon3343",
    phone: "786541235",
    email: "shayon@gmail.com",
    status: "inactive",
  },
  {
    id: 9,
    name: "Clinton Biswas",
    username: "ponti3343",
    phone: "01726288542",
    email: "ponti@gmail.com",
    status: "active",
  },
  {
    id: 10,
    name: "Ponti Biswas",
    username: "clinton3343",
    phone: "4532134567",
    email: "clinton@gmail.com",
    status: "inactive",
  },
  {
    id: 11,
    name: "Anik Biswas",
    username: "Anik3343",
    phone: "765431987",
    email: "anik@gmail.com",
    status: "active",
  },
  {
    id: 12,
    name: "Alex Biswas",
    username: "Alex3343",
    phone: "9876543567",
    email: "alex@gmail.com",
    status: "active",
  },
  {
    id: 13,
    name: "Nazirul Biswas",
    username: "Nazirul3343",
    phone: "8765748865",
    email: "nazirul@gmail.com",
    status: "inactive",
  },
  {
    id: 14,
    name: "Shohag Biswas",
    username: "shohag3343",
    phone: "654328765",
    email: "bala@gmail.com",
    status: "active",
  },
  {
    id: 15,
    name: "Sourav Biswas",
    username: "sourav",
    phone: "987654323",
    email: "sourav@gmail.com",
    status: "active",
  },
  {
    id: 16,
    name: "Shayon Biswas",
    username: "shayon3343",
    phone: "786541235",
    email: "shayon@gmail.com",
    status: "inactive",
  },
];
export default Data;
